
//export const ORGANIZATION = "/"
//export const DATA_PRODUCTS = "/products"
export const DATA_PRODUCTS = "/"
export const PRODUCT_EXPLORER = "product_explorer"
export const PRODUCT_MODELS = "product_models"
export const PRODUCT_MANAGE = "product_manage"
export const INVITE_PAGE = "/invite/:teamid/:refid"
export const DOCUMENT = "document"
export const DOCUMENT_EXPLORER = "document_explorer"
export const FEEDBACK = "/feedback"
export const EXAMPLES_PRODUCTS = "/example_products"
export const TOKENS = "/tokens"
export const PROFILE = "/profile"
export const TEAM_MEMBERS = "members"
