
//export const ORGANIZATION = "/"
//export const DATA_PRODUCTS = "/products"
export const DATA_PRODUCTS = "/"
export const PRODUCT_EXPLORER = "product_explorer"
export const PRODUCT_MODELS = "product_models"
export const PRODUCT_MANAGE = "product_manage"
export const INVITE_PAGE = "/invite/:teamid/:refid"
export const DOCUMENT = "document"
//export const DOCUMENT_EXPLORER = "document_explorer"
export const DOCUMENT_EXPLORER = "documents"
export const FEEDBACK = "/feedback"
export const EXAMPLES_PRODUCTS = "/example_products"
export const TOKENS = "/tokens"
export const PROFILE = "profile"
export const TEAM_MEMBERS = "members"

export const CHANGE_REQUESTS = "change_requests"
export const NEW_DOC = "___NEW_DOC___"
export const EDIT_DOC = "___EDIT_DOC___"
export const MEMBERS = "members"
