export const CREATE_DOCUMENT = "Create"
export const EDIT_DOCUMENT = "Edit"
export const UPDATE_DOCUMENT = "Update"
export const VIEW_DOCUMENT = "View"
export const DELETE_DOCUMENT = "Delete"
export const GET_FRAMES_DOCUMENT = "Frames"

export const TABLE_VIEW = "TABLE"
export const GRAPH_VIEW = "GRAPH"
export const JSON_VIEW = "JSON"
export const FORM_VIEW="FORM"