export const ADD_NEW_ENTITY="ADD_NEW_ENTITY";
export const ADD_NEW_CLASS="ADD_NEW_CLASS";
export const ADD_NEW_CHOICE_CLASS="ADD_NEW_CHOICE_CLASS";

export const ADD_PARENT="ADD_PARENT";
export const REMOVE_PARENT="REMOVE_PARENT";
export const ADD_CHILD="ADD_CHILD";
export const REMOVE_CHILD="REMOVE_CHILD";

export const ADD_PROPERTY="ADD_PROPERTY";
export const REMOVE_PROPERTY="REMOVE_PROPERTY";
